Repository PeopleForBikes/measure, pull requests merged in 2022-03, with the labels that each got.

#9 Setup the project with Poetry
  .github/workflows/ci-python-just.yml
  environment-macos-aarch64.yaml
  environment.yaml
  justfile
  poetry.lock
  poetry.toml
  pyproject.toml
  requirements.txt
  setup.cfg
Labels: size/XXL

#11 Add data models
  .pylintrc
  justfile
  measure/models.py
  poetry.lock
  pyproject.toml
Labels: size/XL

#12 Add Sphinx documentation
  README.md
  docs/Makefile
  docs/make.bat
  docs/source/CHANGELOG.md
  docs/source/README.md
  docs/source/api/measure.rst
  docs/source/api/modules.rst
  docs/source/conf.py
  docs/source/index.rst
  justfile
  measure/models.py
  setup.cfg
Labels: size/L

#13 Add JupyterLab and fix typo
  justfile
  poetry.lock
  pyproject.toml
Labels: size/XXL
